---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
- name: ubuntu-14.04
- name: centos-6.5

suites:
- name: default
  run_list:
    - recipe[golang_test::default]
    - recipe[minitest-handler]
  attributes:
    go:
      owner: 'vagrant'
      group: 'vagrant'
- name: src
  run_list:
    - recipe[golang_test::default]
    - recipe[minitest-handler]
  attributes:
    go:
      from_source: true
      arch: 'amd64'
      owner: 'vagrant'
      group: 'vagrant'
      version: '1.4'
- name: bootstrap
  run_list:
    - recipe[golang::bootstrap]
    - recipe[golang_test::default]
    - recipe[minitest-handler]
  attributes:
    go:
      from_source: true
      arch: 'amd64'
      owner: 'vagrant'
      group: 'vagrant'
      version: '1.5.1'
      bootstrap_url: https://bintray.com/artifact/download/rollbrettler/generic/go-linux-amd64-bootstrap.tbz
